# Generated by Django 3.2.5 on 2021-07-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleaniness',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
